### ISSUE TITLE
Q: Why <thead><tr><TD> or not <th>?

### ISSUE THREAD

**Issue by Valexr** [autr/svelte-tabular-table#1]
& how I can set to cell custom value/component? Something like this:

![Screenshot 2021-04-27 at 13 30 44](https://user-images.githubusercontent.com/5656366/116227429-cf332f00-a75c-11eb-8404-31aa7bc8d0fa.jpg)

**Comment by autr** [comment]
Hey @Valexr - well spotted with TD / TH, I'll make a fix for that.

For customer cell components, check the [example here](https://autr.github.io/svelte-tabular-table/#components):

```
<script>
import Auto from './Auto.svelte'
import { Table } from 'svelte-tabular-table'
const config = {
	init: {
		keys: ['picture', 'name', 'latitude', 'longitude', 'registered', 'about'],
		index: '_id',
		data
	},
	callbacks: {
		render: {
			cell: Auto,
			key: Auto
		}
	},
}
</script>
```

Where Auto.svelte has the properties:

```
<script>
	export let id
	export let item
	export let key
	export let value
	export let index
	export let type
</script>
```

**Comment by Valexr** [comment]
> Hey @Valexr - well spotted with TD / TH, I'll make a fix for that.
> 
> For custom cell components, check the [example here](https://autr.github.io/svelte-tabular-table/#components):
> 
> ```
> <script>
> import Auto from './Auto.svelte'
> import { Table } from 'svelte-tabular-table'
> const config = {
> 	init: {
> 		keys: ['picture', 'name', 'latitude', 'longitude', 'registered', 'about'],
> 		index: '_id',
> 		data
> 	},
> 	callbacks: {
> 		render: {
> 			cell: Auto,
> 			key: Auto
> 		}
> 	},
> }
> </script>
> ```
> 
> Where Auto.svelte has the properties:
> 
> ```
> <script>
> 	export let id
> 	export let item
> 	export let key
> 	export let value
> 	export let index
> 	export let type
> </script>
> ```
> 
> This can also be a callback instead:
> 
> ```
> 	callbacks: {
> 		render: {
> 			cell: o => 'This is a body cell' ,
> 			key: o => 'This is a header cell',
> 		}
> 	}
> </script>
> ```

Ok👌🏻but how I can get index of value to cell ?

**Comment by autr** [comment]
An integer index is returned either as `export let index` property in the SvelteComponent or in the object returned by a callback.

Ideally though use `id` instead of the integer index as it ensures nothing gets mixed up if the data changes or is sorted / rearranged. For example:

```
init: {
  index: 'id',
  data: [ { id: 'unique001' }, { id: 'unique002' }, etc... ]
}
```

Or:

```
init: {
  index: 'customKey',
  data: [ { customKey: 'unique001' }, { customKey: 'unique002' }, etc... ]
}
```

**Comment by Valexr** [comment]
> An integer index is returned either as `export let index` property in the SvelteComponent or in the object returned by a callback.
> 
> Ideally though use `id` instead of the integer index as it ensures nothing gets mixed up if the data changes or is sorted / rearranged. For example:
> 
> ```
> init: {
>   index: 'id',
>   data: [ { id: 'unique001' }, { id: 'unique002' }, etc... ]
> }
> ```
> 
> Or:
> 
> ```
> init: {
>   index: 'customKey',
>   data: [ { customKey: 'unique001' }, { customKey: 'unique002' }, etc... ]
> }
> ```

`export let index` always returned `1`... & tx🤓 I have unic indexes...

**Comment by autr** [comment]
Hey @Valexr , just pushed a bunch of improvements and fixes (v1.0.6)

The render callbacks and components now return with `rowIndex` and `cellIndex` instead of just `index`

Also added a `classes` property on <Table />, which is a keyed object of classes that will be applied to the row if it contains the row id, for example:

```

let highlightedRows = []

$: classes = {
	active_color_yellow: highlightedRows
}

let callbacks = {
		click: {
			cell: o => {
				highlightedRows.push( o.id )
			}
		}
	}
}

<Table {classes} {init} {callbacks} />

```

Hope that helps! [Docs example here](https://autr.github.io/svelte-tabular-table/#classes)

**Comment by Valexr** [comment]
Oh, tx @autr will see…

**Comment by Valexr** [comment]
& what about thead > td / th ?

**Comment by autr** [comment]
Yep, there since 1.0.5

<img width="544" alt="Screenshot 2021-05-06 at 20 53 21" src="https://user-images.githubusercontent.com/56603487/117350696-26e43f80-aead-11eb-92e6-ac6e190e7310.png">
